### ISSUE TITLE
Can't Merge Into procrasti/k666

### ISSUE THREAD

**Issue by procrasti** [orionblastar/FreeK666backup#3]
You lost the branch information somewhere along the way.

That complicates all the github tracking.

Start again with k666 as a fork of procrasti/k666, and then do what you have to do to make k666 the same as freek666, then decide what you want to do.

**Comment by procrasti** [comment]
Alright... K666 exists at least, and kr5ddit can merge it... so, that's great...

But I think you going to have rename this repository, and fork a new one from K666 called FreeK666.

I don't know... they're your bugs...

But I want to see more than the .gitignore... where's freek666 module gone in the K666 repository?

**Comment by procrasti** [comment]
Okay, maybe just leave this as it is for now, and make sure you've gotten everything from it... and I'll recreate the project issues in the K666 repository.

**Comment by orionblastar** [comment]
FreeK666Backup this repository is renamed to. I just merged files from OrionBlastar/K666/Tree/FreeK666 into OrionBlastar/FreeK666backup we got to the point that it has an HTML static file and some pictures and other stuff, so it is at a stable release even if it doesn't do much.

OB/K666 is the new fork of your P/K666

**Comment by procrasti** [comment]
Yep... I think I can close this... you can deal with getting the FreeK666 repo up and running.
