### ISSUE TITLE
Copyright problems....

### ISSUE THREAD

**Issue by procrasti** [orionblastar/FreeK666backup#4]
And... we will have to fix this... I think the upvote and downvote images are infringing a bit on our brandname, which is kr5ddit... so, you can't really use that... just make em upvote and downvote then that's all good.

**Comment by orionblastar** [comment]
I'll fix them in OrionBlastar/K666 FreeK666 branch

**Comment by orionblastar** [comment]
I made upvote and downvote arrows. Blue for up and red for down. To replace the Kr5ddit arrows.

**Comment by orionblastar** [comment]
They are in OB/K666 in the freek666/static/images directory.

**Comment by procrasti** [comment]
Yeah, I'll close this too... We can bring it back up in K666 or whatever else in the future... this repo is effectively dead.
